feat: Added more command line functions
Also added more pretty formatting, and updated the help

diff --git a/custom-resolution-helper b/custom-resolution-helper
--- a/custom-resolution-helper
+++ b/custom-resolution-helper
@@ -3,13 +3,28 @@ set -eo pipefail
 source /usr/lib/ujust/ujust.sh
 source /etc/os-release
 
-helptext="====== Custom Resolution Helper Util ======
+helptext="${bold}====== Custom Resolution Helper Util ======${normal}
 
 This tool helps with setting a custom resolution using modedb kernel arguments.
 
-Usage: $(basename "$0")
+${bold}Usage:${normal} $(basename "$0") [OPTION] [ARGUMENT]
 
-This is currently only an interactive tool, for now.
+${bold}Options:${normal}
+  current             Show current custom resolutions
+  add [RESOLUTION]    Add a custom resolution
+  rm [RESOLUTION]     Remove a custom resolution
+  rm all              Remove all custom resolutions
+
+${bold}[RESOLUTION]${normal} must be in the form of ${bold}<name>:<xres>x<yres>[M][R][-<bpp>][@<refresh>][i][m][eDd]${normal}
+  For detailed explaination, see https://www.kernel.org/doc/Documentation/fb/modedb.txt
+
+${bold}Examples:${normal}
+  $(basename "$0") current
+  $(basename "$0") add [RESOLUTION]
+  $(basename "$0") rm [RESOLUTION]
+  $(basename "$0") rm all
+
+${bold}For help${normal}: https://discord.bazzite.gg
 "
 
 #Utility functions, mostly copied from brh
@@ -25,7 +40,20 @@ press_any_key() {
   read -r
 }
 
+confirm_reboot() {
+  if [[ "$1" == "-y" ]]; then
+    echo "The system will reboot in 5 seconds!"
+    sleep 5
+    systemctl reboot
+  else
+    if confirm "Reboot now?"; then
+      systemctl reboot
+    fi
+  fi
+}
+
 print_status() {
+  KARGS=$(rpm-ostree kargs)
   echo -n "Current custom resolution(s) are: "
   MODEDB_OPTS=$(echo "$KARGS" | grep -oP 'video=\K[^ ]*')
   if [ -z "$MODEDB_OPTS" ]; then
@@ -40,7 +68,7 @@ print_status() {
 }
 
 #Usage Functions
-add() {
+add_to() {
   echo "Select a monitor, this should be any one of the connected ports."
   MONITOR_OPTS=$(gum choose $(for p in /sys/class/drm/*/status; do
     con=${p%/status};
@@ -51,7 +79,7 @@ add() {
   fi
   echo "$(echo "$MONITOR_OPTS" | grep -o '^[^:]*')"
   ADD_MONITOR=$(echo "$(echo "$MONITOR_OPTS" | grep -o '^[^:]*')")
-  #The final form is <xres>x<yres>[M][R][-<bpp>][@<refresh>][i][m] according to the kernel modedb docs
+  #The final form is <xres>x<yres>[M][R][-<bpp>][@<refresh>][i][m][eDd] according to the kernel modedb docs
   local xyres=''
   local refresh=''
   local M=''
@@ -88,7 +116,7 @@ add() {
   if confirm "Do you want to add ${bold}margins${normal} to the calculation? (1.8% of xres rounded down to 8 pixels and 1.8% of yres)"; then
     m="m"
   fi
-  if confirm "Do you want to make this display always enabled? (This is useful for making a virtual display for game streaming with Sunshine)"; then
+  if confirm "Do you want to make this display ${bold}always enabled${normal}? (This is useful for making a virtual display for game streaming with Sunshine)"; then
     e="e"
   fi
 
@@ -96,11 +124,20 @@ add() {
   echo "Your kernel argument for the resolution is ${bold}$ADD_RESOLUTION${normal}"
   ADD_KARGS=$(echo -n "--append-if-missing=video=$ADD_RESOLUTION")
   if confirm "Would you like to apply it now?"; then
-    rpm-ostree kargs $ADD_KARGS
+    echo "Adding kernel arguments..."
+    echo "Command: ${bold}rpm-ostree kargs $ADD_KARGS${normal}"
+    if rpm-ostree kargs "$ADD_KARGS"; then
+      echo "${green}Custom resolution added successfully!${normal} Reboot to apply changes."
+      confirm_reboot
+    else
+      echo "${red}Adding kernel arguments failed.${normal} You may have an update in the background."
+      return 1;
+    fi
   else
     echo "Cancelled."
     return 0;
   fi
+
 }
 
 remove() {
@@ -111,7 +148,13 @@ remove() {
   if confirm "Remove ${bold}$RM_RESOLUTION${normal}?"; then
     RM_KARGS=$(echo -n "--delete-if-present=video=$RM_RESOLUTION")
     echo "Command: ${bold}rpm-ostree kargs $RM_KARGS${normal}"
-    rpm-ostree kargs $RM_KARGS
+    if rpm-ostree kargs "$RM_KARGS"; then
+      echo "${green}Custom resolution removed successfully!${normal} Reboot to apply changes."
+      confirm_reboot "$1"
+    else
+      echo "${red}Removing kernel arguments failed.${normal} You may have an update in the background."
+      return 1;
+    fi
   else
     echo "Cancelled."
     return 0;
@@ -119,18 +162,99 @@ remove() {
 }
 
 removeAll() {
-  if confirm "Remove All Custom Resolutions?"; then
+  if [[ "-y" == "$1" ]] ; then
     RM_KARGS=$(for mode_options in "${OPT_ARRAY[@]}"; do
       echo -n "--delete-if-present=video=$mode_options "
       done)
     echo "Command: ${bold}rpm-ostree kargs $RM_KARGS${normal}"
-    rpm-ostree kargs $RM_KARGS
-  else
-    echo "Cancelled."
-    return 0;
+    if rpm-ostree kargs "$RM_KARGS"; then
+      echo "${green}Custom resolution removed successfully!${normal} Reboot to apply changes."
+      confirm_reboot "$1"
+    else
+      echo "${red}Removing kernel arguments failed.${normal} You may have an update in the background."
+      return 1;
+    fi
+  elif confirm "Remove All Custom Resolutions?" ; then
+      RM_KARGS=$(for mode_options in "${OPT_ARRAY[@]}"; do
+        echo -n "--delete-if-present=video=$mode_options "
+        done)
+      echo "Command: ${bold}rpm-ostree kargs $RM_KARGS${normal}"
+      if rpm-ostree kargs "$RM_KARGS"; then
+        echo "${green}Custom resolution removed successfully!${normal} Reboot to apply changes."
+        confirm_reboot "$1"
+      else
+        echo "${red}Removing kernel arguments failed.${normal} You may have an update in the background."
+        return 1;
+      fi
+    else
+      echo "Cancelled."
+      return 0;
   fi
 }
 
+add() {
+  if [[ -z "$1" && -z "$2" ]]; then
+    add_to
+    return 0;
+  fi
+  local res_check=$(echo "$1" | grep -oE ':[0-9]+x[0-9]+[M]?[R]?@[0-9]+[e]?' || :)
+  if [[ $res_check == "" ]]; then
+    echo "Invalid resolution ${bold}$1${normal}"
+    echo >&2 "Usage: add <name>:<xres>x<yres>[M][R][-<bpp>][@<refresh>][i][m][eDd]"
+    echo >&2 "Examples: add DP1:1920x1080MR@75e"
+    echo >&2 "For detailed explaination see ${bold}https://www.kernel.org/doc/Documentation/fb/modedb.txt${normal}"
+    return 1
+  fi
+  echo "Adding kernel arguments..."
+  local ADD_KARGS=$(echo "--append-if-missing=video=$1")
+  echo "Command: ${bold}rpm-ostree kargs $ADD_KARGS${normal}"
+  if rpm-ostree kargs "$ADD_KARGS"; then
+    echo "${green}Custom resolution added successfully!${normal} Reboot to apply changes."
+    confirm_reboot "$2"
+  else
+    echo "${red}Adding kernel arguments failed.${normal} You may have an update in the background."
+    return 1;
+  fi
+}
+
+rm() {
+  print_status
+
+  if [[ -z "$1" && -z "$2" ]]; then
+    remove
+    return 0;
+  fi
+
+  if [[ "all" == "$1" ]]; then
+    removeAll "$2"
+    return 0;
+  fi
+
+  local res_check=$(echo "$1" | grep -oE ':[0-9]+x[0-9]+[M]?[R]?@[0-9]+[e]?' || :)
+  if [[ $res_check == "" ]]; then
+    echo "Invalid resolution ${bold}$1${normal}"
+    echo >&2 "Usage: rm <name>:<xres>x<yres>[M][R][-<bpp>][@<refresh>][i][m][eDd]"
+    echo >&2 "Examples: rm $mode_options"
+    echo >&2 "For detailed explaination see ${bold}https://www.kernel.org/doc/Documentation/fb/modedb.txt${normal}"
+    return 1;
+  fi
+
+  if [[ "$MODEDB_OPTS" =~ "$1" ]]; then
+    echo "Removing kernel arguments..."
+    local RM_KARGS=$(echo "--delete-if-present=video=$1")
+    echo "Command: ${bold}rpm-ostree kargs $RM_KARGS${normal}"
+    if rpm-ostree kargs "$RM_KARGS"; then
+      echo "${green}Custom resolution removed successfully!${normal} Reboot to apply changes."
+      confirm_reboot "$2"
+    else
+      echo "${red}Removing kernel arguments failed.${normal} You may have an update in the background."
+      return 1;
+    fi
+  else
+    echo "The resolution you are trying to remove does not exist!"
+    return 1;
+  fi
+}
 
 interactive_menu(){
   while true; do
@@ -145,7 +269,7 @@ interactive_menu(){
     case "$OPTION" in
       "Add")
         clear
-        add
+        add_to
       ;;
       "Remove")
         clear
@@ -170,7 +294,6 @@ if  [[ "$OSTREE_VERSION" == "" ]]; then
   echo "This is NOT Fedora Atomic, exiting"
   exit 0
 fi
-KARGS=$(rpm-ostree kargs)
 
 OSTREE_STATE=$(rpm-ostree status | grep "idle" || :)
 if [[ "$OSTREE_STATE" != "State: idle" ]]; then
@@ -181,6 +304,8 @@ fi
 
 case "$1" in
   "current") print_status ;;
+  "add") add "$2" "$3" ;;
+  "rm") rm "$2" "$3" ;;
   "help"|"-h"|"--help"|"") interactive_menu ;;
   *) echo "Unknown option: $1. Run without arguments for interactive mode."
 esac
